builders:
  validator:
    import: "package:nice_validator/generator/builder.dart"
    builder_factories: ["validatorBuilder"]
    build_extensions: {".dart": [".nv.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen"]
    defaults:
      options:
        output_extension: ".nv.dart" 
