name: nice_validator
description: Easy, light weight library for annotation based model validation in flutter
version: 1.0.0
repository: https://github.com/voonic/nice_validator

environment:
  sdk: ^3.6.1

dependencies:
  analyzer: ^7.4.5
  source_gen: ^2.0.0
  build: ^2.4.1
  meta: ^1.10.0

dev_dependencies:
  build_runner: ^2.4.6

