name: nice_validator
description: Easy, light weight library for annotation based model validation in flutter
version: 1.0.0
repository: https://github.com/voonic/nice_validator

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
